# Generated by Django 5.2.17 on 2026-08-16 20:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('operators', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('folio', models.CharField(max_length=14, unique=True, verbose_name='Folio')),
                ('load_datetime', models.DateTimeField(verbose_name='Fecha y hora de carga')),
                ('station_name', models.CharField(max_length=120, verbose_name='Estación')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Litros')),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio por litro')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo total')),
                ('odometer_km', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Odómetro (km)')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.delivery', verbose_name='Entrega asociada')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operators.operator', verbose_name='Operador')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Carga de combustible',
                'verbose_name_plural': 'Cargas de combustible',
                'ordering': ['-load_datetime'],
                'indexes': [models.Index(fields=['vehicle', 'load_datetime'], name='fuel_fuello_vehicle_305040_idx')],
            },
        ),
    ]
