# Generated by Django 5.2.17 on 2026-08-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('business_name', models.CharField(max_length=150, verbose_name='Razón social')),
                ('tax_id', models.CharField(max_length=13, verbose_name='RFC')),
                ('contact_name', models.CharField(max_length=120, verbose_name='Contacto')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('city', models.CharField(max_length=80, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=80, verbose_name='Estado')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Código postal')),
                ('customer_type', models.CharField(choices=[('PREMIUM', 'Premium'), ('REGULAR', 'Regular'), ('OCCASIONAL', 'Ocasional')], default='REGULAR', max_length=12, verbose_name='Tipo de cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['code'],
            },
        ),
    ]
