# Generated by Django 5.2.17 on 2026-08-16 20:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('origin_city', models.CharField(max_length=80, verbose_name='Ciudad origen')),
                ('destination_city', models.CharField(max_length=80, verbose_name='Ciudad destino')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Distancia (km)')),
                ('estimated_duration_min', models.PositiveIntegerField(verbose_name='Duración estimada (min)')),
                ('route_type', models.CharField(choices=[('LOCAL', 'Local'), ('REGIONAL', 'Regional'), ('FORANEA', 'Foránea')], default='REGIONAL', max_length=10, verbose_name='Tipo de ruta')),
                ('zone', models.CharField(max_length=40, verbose_name='Zona')),
                ('toll_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Casetas')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['code'],
            },
        ),
    ]
