# Generated by Django 5.2.17 on 2026-08-16 20:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('economic_number', models.CharField(max_length=10, unique=True, verbose_name='Número económico')),
                ('brand', models.CharField(max_length=60, verbose_name='Marca')),
                ('model', models.CharField(max_length=60, verbose_name='Modelo')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Camión'), ('VAN', 'Camioneta'), ('TRAILER', 'Tráiler'), ('PICKUP', 'Pick-up')], default='TRUCK', max_length=10, verbose_name='Tipo')),
                ('cargo_capacity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad de carga (kg)')),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diésel'), ('GASOLINE', 'Gasolina')], default='DIESEL', max_length=10, verbose_name='Combustible')),
                ('tank_capacity_l', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidad de tanque (L)')),
                ('current_odometer_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Odómetro (km)')),
                ('acquisition_date', models.DateField(verbose_name='Fecha de adquisición')),
                ('next_service_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Próximo servicio (km)')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Último servicio')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('ON_ROUTE', 'En ruta'), ('IN_MAINTENANCE', 'En mantenimiento'), ('OUT_OF_SERVICE', 'Fuera de servicio')], default='AVAILABLE', max_length=16, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['economic_number'],
            },
        ),
    ]
