# Generated by Django 5.2.17 on 2026-08-16 21:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('folio', models.CharField(max_length=14, unique=True, verbose_name='Folio')),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo')], default='PREVENTIVE', max_length=12, verbose_name='Tipo')),
                ('service_date', models.DateField(verbose_name='Fecha de servicio')),
                ('odometer_km', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Odómetro (km)')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('workshop', models.CharField(max_length=120, verbose_name='Taller')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Mano de obra')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Refacciones')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo total')),
                ('next_service_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Próximo servicio (km)')),
                ('days_out_of_service', models.PositiveSmallIntegerField(default=0, verbose_name='Días fuera de servicio')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('IN_PROGRESS', 'En proceso'), ('COMPLETED', 'Completado')], default='SCHEDULED', max_length=12, verbose_name='Estatus')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-service_date'],
                'indexes': [models.Index(fields=['vehicle', 'service_date'], name='maintenance_vehicle_53af40_idx')],
            },
        ),
    ]
