# Generated by Django 5.2.17 on 2026-08-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('employee_number', models.CharField(max_length=10, unique=True, verbose_name='Número de empleado')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('license_number', models.CharField(max_length=20, verbose_name='Número de licencia')),
                ('license_type', models.CharField(choices=[('A', 'A — Automovilista'), ('B', 'B — Chofer'), ('C', 'C — Carga federal'), ('E', 'E — Doble remolque')], default='C', max_length=2, verbose_name='Tipo de licencia')),
                ('license_expiry', models.DateField(verbose_name='Vigencia de licencia')),
                ('hire_date', models.DateField(verbose_name='Fecha de ingreso')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('VACATION', 'Vacaciones'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=12, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['employee_number'],
            },
        ),
    ]
