# Generated by Django 5.2.17 on 2026-08-16 20:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('operators', '0001_initial'),
        ('routes', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=80, verbose_name='Causa')),
                ('category', models.CharField(choices=[('EXTERNA', 'Externa'), ('INTERNA', 'Interna'), ('MECANICA', 'Mecánica')], default='EXTERNA', max_length=10, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Causa de retraso',
                'verbose_name_plural': 'Causas de retraso',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('folio', models.CharField(max_length=14, unique=True, verbose_name='Folio')),
                ('scheduled_departure', models.DateTimeField(verbose_name='Salida programada')),
                ('actual_departure', models.DateTimeField(blank=True, null=True, verbose_name='Salida real')),
                ('scheduled_arrival', models.DateTimeField(verbose_name='Llegada programada')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Llegada real')),
                ('cargo_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso de carga (kg)')),
                ('packages_count', models.PositiveIntegerField(default=1, verbose_name='Bultos')),
                ('declared_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor declarado')),
                ('freight_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Flete')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('IN_TRANSIT', 'En tránsito'), ('DELIVERED', 'Entregada'), ('DELAYED', 'Entregada con retraso'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=12, verbose_name='Estatus')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Cliente')),
                ('delay_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deliveries.delaycause', verbose_name='Causa de retraso')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operators.operator', verbose_name='Operador')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='routes.route', verbose_name='Ruta')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-scheduled_departure'],
                'indexes': [models.Index(fields=['scheduled_departure'], name='deliveries__schedul_15645d_idx'), models.Index(fields=['route', 'scheduled_departure'], name='deliveries__route_i_87f664_idx'), models.Index(fields=['vehicle', 'scheduled_departure'], name='deliveries__vehicle_5ab627_idx'), models.Index(fields=['status'], name='deliveries__status_bdfe1b_idx')],
            },
        ),
    ]
